spring:
  #  profile: development
  application:
    name: service-registry

server:
  port: 8761
#??????
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

